/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../../../../../shared/runtime";
import type {
  AssignUserPermissionRequest,
  AssignUserPermissionResponse,
  GetUserPermissionsResponse,
  RevokePermissionRequest,
  RevokePermissionResponse,
} from "../../models/index";
import {
  AssignUserPermissionRequestFromJSON,
  AssignUserPermissionRequestToJSON,
  AssignUserPermissionResponseFromJSON,
  AssignUserPermissionResponseToJSON,
  GetUserPermissionsResponseFromJSON,
  GetUserPermissionsResponseToJSON,
  RevokePermissionRequestFromJSON,
  RevokePermissionRequestToJSON,
  RevokePermissionResponseFromJSON,
  RevokePermissionResponseToJSON,
} from "../../models/index";

export interface PermissionServiceAssignPermissionRequest {
  assignUserPermissionRequest: AssignUserPermissionRequest;
}

export interface PermissionServiceGetUserPermissionsRequest {
  userId: string;
  userId2?: string;
}

export interface PermissionServiceRevokePermissionRequest {
  revokePermissionRequest: RevokePermissionRequest;
}

/**
 * PermissionServiceApi - interface
 *
 * @export
 * @interface PermissionServiceApiInterface
 */
export interface PermissionServiceApiInterface {
  /**
   * Assign a permission to a user or role.
   * Assign Permission
   */
  permissionServiceAssignPermission(
    requestParameters: PermissionServiceAssignPermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AssignUserPermissionResponse>;

  /**
   * Retrieve all permissions assigned to a specific user.
   * Get User Permissions
   */
  permissionServiceGetUserPermissions(
    requestParameters: PermissionServiceGetUserPermissionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetUserPermissionsResponse>;

  /**
   * Revoke a permission from a user or role.
   * Revoke Permission
   */
  permissionServiceRevokePermission(
    requestParameters: PermissionServiceRevokePermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RevokePermissionResponse>;
}

/**
 * Map of operation names to their required OAuth scopes
 */
export interface PermissionServiceApiOperationScopes {
  permissionServiceAssignPermission: readonly string[];
  permissionServiceGetUserPermissions: readonly string[];
  permissionServiceRevokePermission: readonly string[];
}

/**
 * Operation scopes for PermissionServiceApi
 */
export const PermissionServiceApiOperationScopesMap: PermissionServiceApiOperationScopes =
  {
    permissionServiceAssignPermission: ["write:permission"] as const,
    permissionServiceGetUserPermissions: ["read:permission"] as const,
    permissionServiceRevokePermission: ["delete:permission"] as const,
  };

/**
 *
 */
export class PermissionServiceApi extends runtime.BaseAPI {
  public readonly operationScopes: PermissionServiceApiOperationScopes =
    PermissionServiceApiOperationScopesMap;

  /**
   * Assign a permission to a user or role.
   * Assign Permission
   */
  async permissionServiceAssignPermissionRaw(
    requestParameters: PermissionServiceAssignPermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AssignUserPermissionResponse>> {
    if (requestParameters["assignUserPermissionRequest"] == null) {
      throw new runtime.RequiredError(
        "assignUserPermissionRequest",
        'Required parameter "assignUserPermissionRequest" was null or undefined when calling permissionServiceAssignPermission().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token(
        "OAuth2",
        (this.operationScopes["permissionServiceAssignPermission"] ||
          []) as string[],
      );

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/v1/permission/assign`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: AssignUserPermissionRequestToJSON(
          requestParameters["assignUserPermissionRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AssignUserPermissionResponseFromJSON(jsonValue),
    );
  }

  /**
   * Assign a permission to a user or role.
   * Assign Permission
   */
  async permissionServiceAssignPermission(
    requestParameters: PermissionServiceAssignPermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AssignUserPermissionResponse> {
    const response = await this.permissionServiceAssignPermissionRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Retrieve all permissions assigned to a specific user.
   * Get User Permissions
   */
  async permissionServiceGetUserPermissionsRaw(
    requestParameters: PermissionServiceGetUserPermissionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetUserPermissionsResponse>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling permissionServiceGetUserPermissions().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["userId2"] != null) {
      queryParameters["userId"] = requestParameters["userId2"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token(
        "OAuth2",
        (this.operationScopes["permissionServiceGetUserPermissions"] ||
          []) as string[],
      );

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/v1/permission/user/{user_id}`;
    urlPath = urlPath.replace(
      `{${"user_id"}}`,
      encodeURIComponent(String(requestParameters["userId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetUserPermissionsResponseFromJSON(jsonValue),
    );
  }

  /**
   * Retrieve all permissions assigned to a specific user.
   * Get User Permissions
   */
  async permissionServiceGetUserPermissions(
    requestParameters: PermissionServiceGetUserPermissionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetUserPermissionsResponse> {
    const response = await this.permissionServiceGetUserPermissionsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Revoke a permission from a user or role.
   * Revoke Permission
   */
  async permissionServiceRevokePermissionRaw(
    requestParameters: PermissionServiceRevokePermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RevokePermissionResponse>> {
    if (requestParameters["revokePermissionRequest"] == null) {
      throw new runtime.RequiredError(
        "revokePermissionRequest",
        'Required parameter "revokePermissionRequest" was null or undefined when calling permissionServiceRevokePermission().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token(
        "OAuth2",
        (this.operationScopes["permissionServiceRevokePermission"] ||
          []) as string[],
      );

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/v1/permission/revoke`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: RevokePermissionRequestToJSON(
          requestParameters["revokePermissionRequest"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RevokePermissionResponseFromJSON(jsonValue),
    );
  }

  /**
   * Revoke a permission from a user or role.
   * Revoke Permission
   */
  async permissionServiceRevokePermission(
    requestParameters: PermissionServiceRevokePermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RevokePermissionResponse> {
    const response = await this.permissionServiceRevokePermissionRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
