/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Hono } from "hono";
import type { Context, MiddlewareHandler } from "hono";
import { ContentfulStatusCode } from "hono/utils/http-status";
import type { ServiceResult } from "../../../../../shared/runtime";
import type {
  AssignUserPermissionRequest,
  AssignUserPermissionResponse,
  GetUserPermissionsResponse,
  RevokePermissionRequest,
  RevokePermissionResponse,
} from "../../models/index";
import type {
  PermissionServiceAssignPermissionRequest,
  PermissionServiceGetUserPermissionsRequest,
  PermissionServiceRevokePermissionRequest,
} from "./client";

/**
 * Service interface for PermissionServiceApi
 */
export interface PermissionServiceApiImpl {
  /**
   * Assign a permission to a user or role.
   * Assign Permission
   */
  permissionServiceAssignPermission(
    c: Context,
    params: PermissionServiceAssignPermissionRequest,
  ): Promise<ServiceResult<AssignUserPermissionResponse>>;

  /**
   * Retrieve all permissions assigned to a specific user.
   * Get User Permissions
   */
  permissionServiceGetUserPermissions(
    c: Context,
    params: PermissionServiceGetUserPermissionsRequest,
  ): Promise<ServiceResult<GetUserPermissionsResponse>>;

  /**
   * Revoke a permission from a user or role.
   * Revoke Permission
   */
  permissionServiceRevokePermission(
    c: Context,
    params: PermissionServiceRevokePermissionRequest,
  ): Promise<ServiceResult<RevokePermissionResponse>>;
}

/**
 * PermissionServiceApi - Router handler
 * Registers routes with Hono app and delegates to service implementation
 */
export class PermissionServiceApiRouterHandler {
  constructor(
    private app: Hono,
    private service: PermissionServiceApiImpl,
    private middlewares: MiddlewareHandler[] = [],
  ) {
    this.registerRoutes();
  }

  private registerRoutes(): void {
    this.app.post("/v1/permission/assign", ...this.middlewares, async (c) => {
      const params = await this.parsePermissionServiceAssignPermissionParams(c);
      const result = await this.service.permissionServiceAssignPermission(
        c,
        params,
      );

      if (result.ok) {
        return c.json(result.data);
      } else {
        return c.json(
          result.error,
          (result.status ?? 500) as ContentfulStatusCode,
        );
      }
    });

    this.app.get(
      "/v1/permission/user/{user_id}".replace("user_id", ":user_id"),
      ...this.middlewares,
      async (c) => {
        const params =
          await this.parsePermissionServiceGetUserPermissionsParams(c);
        const result = await this.service.permissionServiceGetUserPermissions(
          c,
          params,
        );

        if (result.ok) {
          return c.json(result.data);
        } else {
          return c.json(
            result.error,
            (result.status ?? 500) as ContentfulStatusCode,
          );
        }
      },
    );

    this.app.post("/v1/permission/revoke", ...this.middlewares, async (c) => {
      const params = await this.parsePermissionServiceRevokePermissionParams(c);
      const result = await this.service.permissionServiceRevokePermission(
        c,
        params,
      );

      if (result.ok) {
        return c.json(result.data);
      } else {
        return c.json(
          result.error,
          (result.status ?? 500) as ContentfulStatusCode,
        );
      }
    });
  }

  private async parsePermissionServiceAssignPermissionParams(
    c: Context,
  ): Promise<PermissionServiceAssignPermissionRequest> {
    return {
      assignUserPermissionRequest:
        (await c.req.json()) as unknown as AssignUserPermissionRequest,
    };
  }

  private async parsePermissionServiceGetUserPermissionsParams(
    c: Context,
  ): Promise<PermissionServiceGetUserPermissionsRequest> {
    return {
      userId: c.req.param("user_id"),
      userId2: c.req.query("userId"),
    };
  }

  private async parsePermissionServiceRevokePermissionParams(
    c: Context,
  ): Promise<PermissionServiceRevokePermissionRequest> {
    return {
      revokePermissionRequest:
        (await c.req.json()) as unknown as RevokePermissionRequest,
    };
  }
}
