/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { IdentityServiceApi } from "../client";
import type { IdentityServiceApiOperationScopes } from "../client";

/**
 * Mock implementation of IdentityServiceApi for testing
 */
export const mockIdentityServiceApi: jest.Mocked<IdentityServiceApi> = {
  operationScopes: {} as IdentityServiceApiOperationScopes,
  identityServiceRegister: jest.fn(),
  identityServiceRegisterRaw: jest.fn(),
} as any;

/**
 * Reset mock IdentityServiceApi
 */
export function resetMockIdentityServiceApi(): void {
  (mockIdentityServiceApi.identityServiceRegister as jest.Mock).mockReset();
  (mockIdentityServiceApi.identityServiceRegisterRaw as jest.Mock).mockReset();
}
