/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Context, Next } from "hono";
import type { IdentityServiceApiServerScopeMiddleware } from "../server-middleware";
import type { IdentityServiceApiOperationScopes } from "../client";

/**
 * Mock implementation of IdentityServiceApiServerScopeMiddleware for testing
 */
export const mockIdentityServiceApiServerScopeMiddleware: jest.Mocked<IdentityServiceApiServerScopeMiddleware> =
  {
    operationScopes: {} as IdentityServiceApiOperationScopes,
    validateScopes: jest
      .fn()
      .mockReturnValue(async (c: Context, next: Next) => await next()),
    forOperation: jest
      .fn()
      .mockReturnValue(async (c: Context, next: Next) => await next()),
    configuration: undefined,
  } as any;

/**
 * Reset mock IdentityServiceApiServerScopeMiddleware
 */
export function resetMockIdentityServiceApiServerScopeMiddleware(): void {
  (
    mockIdentityServiceApiServerScopeMiddleware.validateScopes as jest.Mock
  ).mockReset();
  (
    mockIdentityServiceApiServerScopeMiddleware.forOperation as jest.Mock
  ).mockReset();
  (
    mockIdentityServiceApiServerScopeMiddleware.forOperation as jest.Mock
  ).mockReturnValue(async (c: Context, next: Next) => await next());
}
