/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { IdentityServiceApiImpl } from "../router";

/**
 * Mock implementation of IdentityServiceApi for testing
 */
export const mockIdentityServiceApiImpl: jest.Mocked<IdentityServiceApiImpl> = {
  identityServiceRegister: jest.fn(),
};

/**
 * Reset all mocks for IdentityServiceApi
 */
export function resetMockIdentityServiceApiImpl(): void {
  mockIdentityServiceApiImpl.identityServiceRegister.mockReset();
}
