/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AuthServiceApi } from "../client";
import type { AuthServiceApiOperationScopes } from "../client";

/**
 * Mock implementation of AuthServiceApi for testing
 */
export const mockAuthServiceApi: jest.Mocked<AuthServiceApi> = {
  operationScopes: {} as AuthServiceApiOperationScopes,
  authServiceLogin: jest.fn(),
  authServiceLoginRaw: jest.fn(),
} as any;

/**
 * Reset mock AuthServiceApi
 */
export function resetMockAuthServiceApi(): void {
  (mockAuthServiceApi.authServiceLogin as jest.Mock).mockReset();
  (mockAuthServiceApi.authServiceLoginRaw as jest.Mock).mockReset();
}
