/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Context, Next } from "hono";
import type { AuthServiceApiServerScopeMiddleware } from "../server-middleware";
import type { AuthServiceApiOperationScopes } from "../client";

/**
 * Mock implementation of AuthServiceApiServerScopeMiddleware for testing
 */
export const mockAuthServiceApiServerScopeMiddleware: jest.Mocked<AuthServiceApiServerScopeMiddleware> =
  {
    operationScopes: {} as AuthServiceApiOperationScopes,
    validateScopes: jest
      .fn()
      .mockReturnValue(async (c: Context, next: Next) => await next()),
    forOperation: jest
      .fn()
      .mockReturnValue(async (c: Context, next: Next) => await next()),
    configuration: undefined,
  } as any;

/**
 * Reset mock AuthServiceApiServerScopeMiddleware
 */
export function resetMockAuthServiceApiServerScopeMiddleware(): void {
  (
    mockAuthServiceApiServerScopeMiddleware.validateScopes as jest.Mock
  ).mockReset();
  (
    mockAuthServiceApiServerScopeMiddleware.forOperation as jest.Mock
  ).mockReset();
  (
    mockAuthServiceApiServerScopeMiddleware.forOperation as jest.Mock
  ).mockReturnValue(async (c: Context, next: Next) => await next());
}
