/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AuthServiceApiImpl } from "../router";

/**
 * Mock implementation of AuthServiceApi for testing
 */
export const mockAuthServiceApiImpl: jest.Mocked<AuthServiceApiImpl> = {
  authServiceLogin: jest.fn(),
};

/**
 * Reset all mocks for AuthServiceApi
 */
export function resetMockAuthServiceApiImpl(): void {
  mockAuthServiceApiImpl.authServiceLogin.mockReset();
}
