/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../../../../../shared/runtime";
import type { RegisterRequest, RegisterResponse } from "../../models/index";
import {
  RegisterRequestFromJSON,
  RegisterRequestToJSON,
  RegisterResponseFromJSON,
  RegisterResponseToJSON,
} from "../../models/index";

export interface IdentityServiceRegisterRequest {
  registerRequest: RegisterRequest;
}

/**
 * IdentityServiceApi - interface
 *
 * @export
 * @interface IdentityServiceApiInterface
 */
export interface IdentityServiceApiInterface {
  /**
   * register new user.
   * Register New User
   */
  identityServiceRegister(
    requestParameters: IdentityServiceRegisterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RegisterResponse>;
}

/**
 * Map of operation names to their required OAuth scopes
 */
export interface IdentityServiceApiOperationScopes {
  identityServiceRegister: readonly string[];
}

/**
 * Operation scopes for IdentityServiceApi
 */
export const IdentityServiceApiOperationScopesMap: IdentityServiceApiOperationScopes =
  {
    identityServiceRegister: [] as const,
  };

/**
 *
 */
export class IdentityServiceApi extends runtime.BaseAPI {
  public readonly operationScopes: IdentityServiceApiOperationScopes =
    IdentityServiceApiOperationScopesMap;

  /**
   * register new user.
   * Register New User
   */
  async identityServiceRegisterRaw(
    requestParameters: IdentityServiceRegisterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<RegisterResponse>> {
    if (requestParameters["registerRequest"] == null) {
      throw new runtime.RequiredError(
        "registerRequest",
        'Required parameter "registerRequest" was null or undefined when calling identityServiceRegister().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token(
        "OAuth2",
        (this.operationScopes["identityServiceRegister"] || []) as string[],
      );

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/v1/identity/register`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: RegisterRequestToJSON(requestParameters["registerRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RegisterResponseFromJSON(jsonValue),
    );
  }

  /**
   * register new user.
   * Register New User
   */
  async identityServiceRegister(
    requestParameters: IdentityServiceRegisterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<RegisterResponse> {
    const response = await this.identityServiceRegisterRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
