/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Hono } from "hono";
import type { Context, MiddlewareHandler } from "hono";
import { ContentfulStatusCode } from "hono/utils/http-status";
import type { ServiceResult } from "../../../../../shared/runtime";
import type { RegisterRequest, RegisterResponse } from "../../models/index";
import type { IdentityServiceRegisterRequest } from "./client";

/**
 * Service interface for IdentityServiceApi
 */
export interface IdentityServiceApiImpl {
  /**
   * register new user.
   * Register New User
   */
  identityServiceRegister(
    c: Context,
    params: IdentityServiceRegisterRequest,
  ): Promise<ServiceResult<RegisterResponse>>;
}

/**
 * IdentityServiceApi - Router handler
 * Registers routes with Hono app and delegates to service implementation
 */
export class IdentityServiceApiRouterHandler {
  constructor(
    private app: Hono,
    private service: IdentityServiceApiImpl,
    private middlewares: MiddlewareHandler[] = [],
  ) {
    this.registerRoutes();
  }

  private registerRoutes(): void {
    this.app.post("/v1/identity/register", ...this.middlewares, async (c) => {
      const params = await this.parseIdentityServiceRegisterParams(c);
      const result = await this.service.identityServiceRegister(c, params);

      if (result.ok) {
        return c.json(result.data);
      } else {
        return c.json(
          result.error,
          (result.status ?? 500) as ContentfulStatusCode,
        );
      }
    });
  }

  private async parseIdentityServiceRegisterParams(
    c: Context,
  ): Promise<IdentityServiceRegisterRequest> {
    return {
      registerRequest: (await c.req.json()) as unknown as RegisterRequest,
    };
  }
}
