/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Context, Next } from "hono";
import type { Configuration } from "../../../../../shared/runtime";
import { IdentityServiceApiOperationScopesMap } from "./client";
import type { IdentityServiceApiOperationScopes } from "./client";

/**
 * OAuth scope validation middleware for IdentityServiceApi
 */
export class IdentityServiceApiServerScopeMiddleware {
  public readonly operationScopes: IdentityServiceApiOperationScopes =
    IdentityServiceApiOperationScopesMap;

  constructor(private configuration?: Configuration) {}

  /**
   * Middleware to validate OAuth scopes for an operation
   * @param operationName - The name of the operation to validate scopes for
   */
  validateScopes(operationName: keyof IdentityServiceApiOperationScopes) {
    return async (c: Context, next: Next) => {
      const requiredScopes = this.operationScopes[operationName] || [];

      if (requiredScopes.length === 0) {
        // No scopes required, continue
        return await next();
      }

      if (!this.configuration?.accessToken) {
        // No access token configuration, reject
        return c.json(
          { error: "Unauthorized", message: "No authentication configured" },
          401,
        );
      }

      try {
        // Get the access token
        const token = this.configuration.accessToken;
        const tokenString =
          typeof token === "function"
            ? await token("OAuth2", requiredScopes as string[])
            : token;

        if (!tokenString) {
          return c.json(
            { error: "Unauthorized", message: "No valid access token" },
            401,
          );
        }

        // Store token in context for service to use
        c.set("accessToken", tokenString);
        c.set("requiredScopes", requiredScopes);

        return await next();
      } catch (error) {
        return c.json(
          {
            error: "Forbidden",
            message: "Insufficient permissions",
            requiredScopes,
          },
          403,
        );
      }
    };
  }

  /**
   * Get middleware for a specific operation
   * @param operationName - The name of the operation
   */
  forOperation(operationName: keyof IdentityServiceApiOperationScopes) {
    return this.validateScopes(operationName);
  }
}
