/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PermissionServiceApi } from "../client";
import type { PermissionServiceApiOperationScopes } from "../client";

/**
 * Mock implementation of PermissionServiceApi for testing
 */
export const mockPermissionServiceApi: jest.Mocked<PermissionServiceApi> = {
  operationScopes: {} as PermissionServiceApiOperationScopes,
  permissionServiceAssignPermission: jest.fn(),
  permissionServiceAssignPermissionRaw: jest.fn(),
  permissionServiceGetUserPermissions: jest.fn(),
  permissionServiceGetUserPermissionsRaw: jest.fn(),
  permissionServiceRevokePermission: jest.fn(),
  permissionServiceRevokePermissionRaw: jest.fn(),
} as any;

/**
 * Reset mock PermissionServiceApi
 */
export function resetMockPermissionServiceApi(): void {
  (
    mockPermissionServiceApi.permissionServiceAssignPermission as jest.Mock
  ).mockReset();
  (
    mockPermissionServiceApi.permissionServiceAssignPermissionRaw as jest.Mock
  ).mockReset();
  (
    mockPermissionServiceApi.permissionServiceGetUserPermissions as jest.Mock
  ).mockReset();
  (
    mockPermissionServiceApi.permissionServiceGetUserPermissionsRaw as jest.Mock
  ).mockReset();
  (
    mockPermissionServiceApi.permissionServiceRevokePermission as jest.Mock
  ).mockReset();
  (
    mockPermissionServiceApi.permissionServiceRevokePermissionRaw as jest.Mock
  ).mockReset();
}
