/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Context, Next } from "hono";
import type { PermissionServiceApiServerScopeMiddleware } from "../server-middleware";
import type { PermissionServiceApiOperationScopes } from "../client";

/**
 * Mock implementation of PermissionServiceApiServerScopeMiddleware for testing
 */
export const mockPermissionServiceApiServerScopeMiddleware: jest.Mocked<PermissionServiceApiServerScopeMiddleware> =
  {
    operationScopes: {} as PermissionServiceApiOperationScopes,
    validateScopes: jest
      .fn()
      .mockReturnValue(async (c: Context, next: Next) => await next()),
    forOperation: jest
      .fn()
      .mockReturnValue(async (c: Context, next: Next) => await next()),
    configuration: undefined,
  } as any;

/**
 * Reset mock PermissionServiceApiServerScopeMiddleware
 */
export function resetMockPermissionServiceApiServerScopeMiddleware(): void {
  (
    mockPermissionServiceApiServerScopeMiddleware.validateScopes as jest.Mock
  ).mockReset();
  (
    mockPermissionServiceApiServerScopeMiddleware.forOperation as jest.Mock
  ).mockReset();
  (
    mockPermissionServiceApiServerScopeMiddleware.forOperation as jest.Mock
  ).mockReturnValue(async (c: Context, next: Next) => await next());
}
