/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PermissionServiceApiImpl } from "../router";

/**
 * Mock implementation of PermissionServiceApi for testing
 */
export const mockPermissionServiceApiImpl: jest.Mocked<PermissionServiceApiImpl> =
  {
    permissionServiceAssignPermission: jest.fn(),
    permissionServiceGetUserPermissions: jest.fn(),
    permissionServiceRevokePermission: jest.fn(),
  };

/**
 * Reset all mocks for PermissionServiceApi
 */
export function resetMockPermissionServiceApiImpl(): void {
  mockPermissionServiceApiImpl.permissionServiceAssignPermission.mockReset();
  mockPermissionServiceApiImpl.permissionServiceGetUserPermissions.mockReset();
  mockPermissionServiceApiImpl.permissionServiceRevokePermission.mockReset();
}
