/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Context } from "hono";

/**
 * Create a mock Hono Context for testing
 */
export function createMockContext(overrides?: Partial<Context>): Context {
  const mockRequest = {
    param: jest.fn((key: string) => undefined),
    query: jest.fn((key: string) => undefined),
    header: jest.fn((key: string) => undefined),
    json: jest.fn().mockResolvedValue({}),
  };

  const mockContext = {
    req: mockRequest,
    json: jest.fn(
      (data: any, status?: number) =>
        new Response(JSON.stringify(data), { status: status || 200 }),
    ),
    text: jest.fn(
      (text: string, status?: number) =>
        new Response(text, { status: status || 200 }),
    ),
    html: jest.fn(
      (html: string, status?: number) =>
        new Response(html, {
          status: status || 200,
          headers: { "Content-Type": "text/html" },
        }),
    ),
    redirect: jest.fn(
      (url: string, status?: number) =>
        new Response(null, {
          status: status || 302,
          headers: { Location: url },
        }),
    ),
    notFound: jest.fn(() => new Response("Not Found", { status: 404 })),
    get: jest.fn((key: string) => undefined),
    set: jest.fn((key: string, value: any) => {}),
    ...overrides,
  };

  return mockContext as any;
}
