/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../../../../../shared/runtime";
import type { LoginRequest, LoginResponse } from "../../models/index";
import {
  LoginRequestFromJSON,
  LoginRequestToJSON,
  LoginResponseFromJSON,
  LoginResponseToJSON,
} from "../../models/index";

export interface AuthServiceLoginRequest {
  loginRequest: LoginRequest;
}

/**
 * AuthServiceApi - interface
 *
 * @export
 * @interface AuthServiceApiInterface
 */
export interface AuthServiceApiInterface {
  /**
   * Logging in User by supported Authentication Factor, \'password\' for password login flow and \'otp_key\' for passwordless login flow.
   * Logging in User by supported Authentication Factor
   */
  authServiceLogin(
    requestParameters: AuthServiceLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LoginResponse>;
}

/**
 * Map of operation names to their required OAuth scopes
 */
export interface AuthServiceApiOperationScopes {
  authServiceLogin: readonly string[];
}

/**
 * Operation scopes for AuthServiceApi
 */
export const AuthServiceApiOperationScopesMap: AuthServiceApiOperationScopes = {
  authServiceLogin: [] as const,
};

/**
 *
 */
export class AuthServiceApi extends runtime.BaseAPI {
  public readonly operationScopes: AuthServiceApiOperationScopes =
    AuthServiceApiOperationScopesMap;

  /**
   * Logging in User by supported Authentication Factor, \'password\' for password login flow and \'otp_key\' for passwordless login flow.
   * Logging in User by supported Authentication Factor
   */
  async authServiceLoginRaw(
    requestParameters: AuthServiceLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<LoginResponse>> {
    if (requestParameters["loginRequest"] == null) {
      throw new runtime.RequiredError(
        "loginRequest",
        'Required parameter "loginRequest" was null or undefined when calling authServiceLogin().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token(
        "OAuth2",
        (this.operationScopes["authServiceLogin"] || []) as string[],
      );

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/v1/auth/login`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: LoginRequestToJSON(requestParameters["loginRequest"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LoginResponseFromJSON(jsonValue),
    );
  }

  /**
   * Logging in User by supported Authentication Factor, \'password\' for password login flow and \'otp_key\' for passwordless login flow.
   * Logging in User by supported Authentication Factor
   */
  async authServiceLogin(
    requestParameters: AuthServiceLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<LoginResponse> {
    const response = await this.authServiceLoginRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
