/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Hono } from "hono";
import type { Context, MiddlewareHandler } from "hono";
import { ContentfulStatusCode } from "hono/utils/http-status";
import type { ServiceResult } from "../../../../../shared/runtime";
import type { LoginRequest, LoginResponse } from "../../models/index";
import type { AuthServiceLoginRequest } from "./client";

/**
 * Service interface for AuthServiceApi
 */
export interface AuthServiceApiImpl {
  /**
   * Logging in User by supported Authentication Factor, \'password\' for password login flow and \'otp_key\' for passwordless login flow.
   * Logging in User by supported Authentication Factor
   */
  authServiceLogin(
    c: Context,
    params: AuthServiceLoginRequest,
  ): Promise<ServiceResult<LoginResponse>>;
}

/**
 * AuthServiceApi - Router handler
 * Registers routes with Hono app and delegates to service implementation
 */
export class AuthServiceApiRouterHandler {
  constructor(
    private app: Hono,
    private service: AuthServiceApiImpl,
    private middlewares: MiddlewareHandler[] = [],
  ) {
    this.registerRoutes();
  }

  private registerRoutes(): void {
    this.app.post("/v1/auth/login", ...this.middlewares, async (c) => {
      const params = await this.parseAuthServiceLoginParams(c);
      const result = await this.service.authServiceLogin(c, params);

      if (result.ok) {
        return c.json(result.data);
      } else {
        return c.json(
          result.error,
          (result.status ?? 500) as ContentfulStatusCode,
        );
      }
    });
  }

  private async parseAuthServiceLoginParams(
    c: Context,
  ): Promise<AuthServiceLoginRequest> {
    return {
      loginRequest: (await c.req.json()) as unknown as LoginRequest,
    };
  }
}
