/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
/**
 * *
 *  Represents user's address
 * @export
 * @interface Address
 */
export interface Address {
  /**
   * address detail
   * @type {string}
   * @memberof Address
   */
  addressLine1?: string;
  /**
   * address detail
   * @type {string}
   * @memberof Address
   */
  addressLine2?: string;
  /**
   * province / provinsi
   * @type {string}
   * @memberof Address
   */
  administrativeAreaLevel1?: string;
  /**
   * city / kota
   * @type {string}
   * @memberof Address
   */
  administrativeAreaLevel2?: string;
  /**
   * area / kecamatan
   * @type {string}
   * @memberof Address
   */
  administrativeAreaLevel3?: string;
  /**
   * district / kelurahan
   * @type {string}
   * @memberof Address
   */
  administrativeAreaLevel4?: string;
  /**
   * postal code / kode pos
   * @type {string}
   * @memberof Address
   */
  postalCode?: string;
  /**
   * stored latitude coordinate in decimal
   * @type {string}
   * @memberof Address
   */
  latitude?: string;
  /**
   * stored longitude coordinate in decimal
   * @type {string}
   * @memberof Address
   */
  longitude?: string;
}

/**
 * Check if a given object implements the Address interface.
 */
export function instanceOfAddress(value: object): value is Address {
  return true;
}

export function AddressFromJSON(json: any): Address {
  return AddressFromJSONTyped(json, false);
}

export function AddressFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Address {
  if (json == null) {
    return json;
  }
  return {
    addressLine1:
      json["addressLine1"] == null ? undefined : json["addressLine1"],
    addressLine2:
      json["addressLine2"] == null ? undefined : json["addressLine2"],
    administrativeAreaLevel1:
      json["administrativeAreaLevel1"] == null
        ? undefined
        : json["administrativeAreaLevel1"],
    administrativeAreaLevel2:
      json["administrativeAreaLevel2"] == null
        ? undefined
        : json["administrativeAreaLevel2"],
    administrativeAreaLevel3:
      json["administrativeAreaLevel3"] == null
        ? undefined
        : json["administrativeAreaLevel3"],
    administrativeAreaLevel4:
      json["administrativeAreaLevel4"] == null
        ? undefined
        : json["administrativeAreaLevel4"],
    postalCode: json["postalCode"] == null ? undefined : json["postalCode"],
    latitude: json["latitude"] == null ? undefined : json["latitude"],
    longitude: json["longitude"] == null ? undefined : json["longitude"],
  };
}

export function AddressToJSON(json: any): Address {
  return AddressToJSONTyped(json, false);
}

export function AddressToJSONTyped(
  value?: Address | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    addressLine1: value["addressLine1"],
    addressLine2: value["addressLine2"],
    administrativeAreaLevel1: value["administrativeAreaLevel1"],
    administrativeAreaLevel2: value["administrativeAreaLevel2"],
    administrativeAreaLevel3: value["administrativeAreaLevel3"],
    administrativeAreaLevel4: value["administrativeAreaLevel4"],
    postalCode: value["postalCode"],
    latitude: value["latitude"],
    longitude: value["longitude"],
  };
}
