/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
/**
 *
 * @export
 * @interface AssignUserPermissionRequest
 */
export interface AssignUserPermissionRequest {
  /**
   * id of user
   * @type {string}
   * @memberof AssignUserPermissionRequest
   */
  userId?: string;
  /**
   * id of rule to be assigned
   * @type {Array<string>}
   * @memberof AssignUserPermissionRequest
   */
  permissionIds?: Array<string>;
}

/**
 * Check if a given object implements the AssignUserPermissionRequest interface.
 */
export function instanceOfAssignUserPermissionRequest(
  value: object,
): value is AssignUserPermissionRequest {
  return true;
}

export function AssignUserPermissionRequestFromJSON(
  json: any,
): AssignUserPermissionRequest {
  return AssignUserPermissionRequestFromJSONTyped(json, false);
}

export function AssignUserPermissionRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssignUserPermissionRequest {
  if (json == null) {
    return json;
  }
  return {
    userId: json["userId"] == null ? undefined : json["userId"],
    permissionIds:
      json["permissionIds"] == null ? undefined : json["permissionIds"],
  };
}

export function AssignUserPermissionRequestToJSON(
  json: any,
): AssignUserPermissionRequest {
  return AssignUserPermissionRequestToJSONTyped(json, false);
}

export function AssignUserPermissionRequestToJSONTyped(
  value?: AssignUserPermissionRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    userId: value["userId"],
    permissionIds: value["permissionIds"],
  };
}
