/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
/**
 *
 * @export
 * @interface AssignUserPermissionResponse
 */
export interface AssignUserPermissionResponse {
  /**
   * message if permission is assigned to user
   * @type {string}
   * @memberof AssignUserPermissionResponse
   */
  message?: string;
}

/**
 * Check if a given object implements the AssignUserPermissionResponse interface.
 */
export function instanceOfAssignUserPermissionResponse(
  value: object,
): value is AssignUserPermissionResponse {
  return true;
}

export function AssignUserPermissionResponseFromJSON(
  json: any,
): AssignUserPermissionResponse {
  return AssignUserPermissionResponseFromJSONTyped(json, false);
}

export function AssignUserPermissionResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssignUserPermissionResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json["message"] == null ? undefined : json["message"],
  };
}

export function AssignUserPermissionResponseToJSON(
  json: any,
): AssignUserPermissionResponse {
  return AssignUserPermissionResponseToJSONTyped(json, false);
}

export function AssignUserPermissionResponseToJSONTyped(
  value?: AssignUserPermissionResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value["message"],
  };
}
