/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
/**
 *
 * @export
 * @interface CursorPagination
 */
export interface CursorPagination {
  /**
   *
   * @type {number}
   * @memberof CursorPagination
   */
  limit?: number;
  /**
   *
   * @type {string}
   * @memberof CursorPagination
   */
  nextCursor?: string;
  /**
   *
   * @type {string}
   * @memberof CursorPagination
   */
  prevCursor?: string;
  /**
   *
   * @type {string}
   * @memberof CursorPagination
   */
  currCursor?: string;
}

/**
 * Check if a given object implements the CursorPagination interface.
 */
export function instanceOfCursorPagination(
  value: object,
): value is CursorPagination {
  return true;
}

export function CursorPaginationFromJSON(json: any): CursorPagination {
  return CursorPaginationFromJSONTyped(json, false);
}

export function CursorPaginationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CursorPagination {
  if (json == null) {
    return json;
  }
  return {
    limit: json["limit"] == null ? undefined : json["limit"],
    nextCursor: json["nextCursor"] == null ? undefined : json["nextCursor"],
    prevCursor: json["prevCursor"] == null ? undefined : json["prevCursor"],
    currCursor: json["currCursor"] == null ? undefined : json["currCursor"],
  };
}

export function CursorPaginationToJSON(json: any): CursorPagination {
  return CursorPaginationToJSONTyped(json, false);
}

export function CursorPaginationToJSONTyped(
  value?: CursorPagination | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    limit: value["limit"],
    nextCursor: value["nextCursor"],
    prevCursor: value["prevCursor"],
    currCursor: value["currCursor"],
  };
}
