/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
/**
 *
 * @export
 * @interface ErrorInfo
 */
export interface ErrorInfo {
  /**
   *
   * @type {string}
   * @memberof ErrorInfo
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof ErrorInfo
   */
  code?: string;
  /**
   *
   * @type {string}
   * @memberof ErrorInfo
   */
  field?: string;
  /**
   *
   * @type {string}
   * @memberof ErrorInfo
   */
  info?: string;
}

/**
 * Check if a given object implements the ErrorInfo interface.
 */
export function instanceOfErrorInfo(value: object): value is ErrorInfo {
  return true;
}

export function ErrorInfoFromJSON(json: any): ErrorInfo {
  return ErrorInfoFromJSONTyped(json, false);
}

export function ErrorInfoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ErrorInfo {
  if (json == null) {
    return json;
  }
  return {
    message: json["message"] == null ? undefined : json["message"],
    code: json["code"] == null ? undefined : json["code"],
    field: json["field"] == null ? undefined : json["field"],
    info: json["info"] == null ? undefined : json["info"],
  };
}

export function ErrorInfoToJSON(json: any): ErrorInfo {
  return ErrorInfoToJSONTyped(json, false);
}

export function ErrorInfoToJSONTyped(
  value?: ErrorInfo | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value["message"],
    code: value["code"],
    field: value["field"],
    info: value["info"],
  };
}
