/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
import type { ErrorInfo } from "./ErrorInfo";
import {
  ErrorInfoFromJSON,
  ErrorInfoFromJSONTyped,
  ErrorInfoToJSON,
  ErrorInfoToJSONTyped,
} from "./ErrorInfo";

/**
 *
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
  /**
   *
   * @type {Array<ErrorInfo>}
   * @memberof ErrorResponse
   */
  errors?: Array<ErrorInfo>;
}

/**
 * Check if a given object implements the ErrorResponse interface.
 */
export function instanceOfErrorResponse(value: object): value is ErrorResponse {
  return true;
}

export function ErrorResponseFromJSON(json: any): ErrorResponse {
  return ErrorResponseFromJSONTyped(json, false);
}

export function ErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ErrorResponse {
  if (json == null) {
    return json;
  }
  return {
    errors:
      json["errors"] == null
        ? undefined
        : (json["errors"] as Array<any>).map(ErrorInfoFromJSON),
  };
}

export function ErrorResponseToJSON(json: any): ErrorResponse {
  return ErrorResponseToJSONTyped(json, false);
}

export function ErrorResponseToJSONTyped(
  value?: ErrorResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    errors:
      value["errors"] == null
        ? undefined
        : (value["errors"] as Array<any>).map(ErrorInfoToJSON),
  };
}
