/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
import type { ResponseMetadata } from "./ResponseMetadata";
import {
  ResponseMetadataFromJSON,
  ResponseMetadataFromJSONTyped,
  ResponseMetadataToJSON,
  ResponseMetadataToJSONTyped,
} from "./ResponseMetadata";
import type { UserPermission } from "./UserPermission";
import {
  UserPermissionFromJSON,
  UserPermissionFromJSONTyped,
  UserPermissionToJSON,
  UserPermissionToJSONTyped,
} from "./UserPermission";

/**
 *
 * @export
 * @interface GetUserPermissionsResponse
 */
export interface GetUserPermissionsResponse {
  /**
   * List of permissions assigned to the user
   * @type {Array<UserPermission>}
   * @memberof GetUserPermissionsResponse
   */
  userPermissions?: Array<UserPermission>;
  /**
   * Metadata about the response
   * @type {ResponseMetadata}
   * @memberof GetUserPermissionsResponse
   */
  meta?: ResponseMetadata;
}

/**
 * Check if a given object implements the GetUserPermissionsResponse interface.
 */
export function instanceOfGetUserPermissionsResponse(
  value: object,
): value is GetUserPermissionsResponse {
  return true;
}

export function GetUserPermissionsResponseFromJSON(
  json: any,
): GetUserPermissionsResponse {
  return GetUserPermissionsResponseFromJSONTyped(json, false);
}

export function GetUserPermissionsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetUserPermissionsResponse {
  if (json == null) {
    return json;
  }
  return {
    userPermissions:
      json["userPermissions"] == null
        ? undefined
        : (json["userPermissions"] as Array<any>).map(UserPermissionFromJSON),
    meta:
      json["meta"] == null ? undefined : ResponseMetadataFromJSON(json["meta"]),
  };
}

export function GetUserPermissionsResponseToJSON(
  json: any,
): GetUserPermissionsResponse {
  return GetUserPermissionsResponseToJSONTyped(json, false);
}

export function GetUserPermissionsResponseToJSONTyped(
  value?: GetUserPermissionsResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    userPermissions:
      value["userPermissions"] == null
        ? undefined
        : (value["userPermissions"] as Array<any>).map(UserPermissionToJSON),
    meta: ResponseMetadataToJSON(value["meta"]),
  };
}
