/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
import type { LoginEntity } from "./LoginEntity";
import {
  LoginEntityFromJSON,
  LoginEntityFromJSONTyped,
  LoginEntityToJSON,
  LoginEntityToJSONTyped,
} from "./LoginEntity";

/**
 *
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
  /**
   * additional information
   * @type {string}
   * @memberof LoginResponse
   */
  message?: string;
  /**
   *
   * @type {LoginEntity}
   * @memberof LoginResponse
   */
  loginEntity?: LoginEntity;
  /**
   * url redirection when login is success or fail
   * @type {string}
   * @memberof LoginResponse
   */
  redirectTo?: string;
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): value is LoginResponse {
  return true;
}

export function LoginResponseFromJSON(json: any): LoginResponse {
  return LoginResponseFromJSONTyped(json, false);
}

export function LoginResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LoginResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json["message"] == null ? undefined : json["message"],
    loginEntity:
      json["loginEntity"] == null
        ? undefined
        : LoginEntityFromJSON(json["loginEntity"]),
    redirectTo: json["redirectTo"] == null ? undefined : json["redirectTo"],
  };
}

export function LoginResponseToJSON(json: any): LoginResponse {
  return LoginResponseToJSONTyped(json, false);
}

export function LoginResponseToJSONTyped(
  value?: LoginResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value["message"],
    loginEntity: LoginEntityToJSON(value["loginEntity"]),
    redirectTo: value["redirectTo"],
  };
}
