/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
/**
 * Login entity
 * @export
 * @interface LoginEntity
 */
export interface LoginEntity {
  /**
   *
   * @type {string}
   * @memberof LoginEntity
   */
  sessionToken?: string;
  /**
   *
   * @type {string}
   * @memberof LoginEntity
   */
  refreshToken?: string;
}

/**
 * Check if a given object implements the LoginEntity interface.
 */
export function instanceOfLoginEntity(value: object): value is LoginEntity {
  return true;
}

export function LoginEntityFromJSON(json: any): LoginEntity {
  return LoginEntityFromJSONTyped(json, false);
}

export function LoginEntityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LoginEntity {
  if (json == null) {
    return json;
  }
  return {
    sessionToken:
      json["sessionToken"] == null ? undefined : json["sessionToken"],
    refreshToken:
      json["refreshToken"] == null ? undefined : json["refreshToken"],
  };
}

export function LoginEntityToJSON(json: any): LoginEntity {
  return LoginEntityToJSONTyped(json, false);
}

export function LoginEntityToJSONTyped(
  value?: LoginEntity | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    sessionToken: value["sessionToken"],
    refreshToken: value["refreshToken"],
  };
}
