/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
/**
 *
 * @export
 * @interface OffsetPagination
 */
export interface OffsetPagination {
  /**
   *
   * @type {number}
   * @memberof OffsetPagination
   */
  limit?: number;
  /**
   *
   * @type {number}
   * @memberof OffsetPagination
   */
  offset?: number;
  /**
   *
   * @type {number}
   * @memberof OffsetPagination
   */
  total?: number;
}

/**
 * Check if a given object implements the OffsetPagination interface.
 */
export function instanceOfOffsetPagination(
  value: object,
): value is OffsetPagination {
  return true;
}

export function OffsetPaginationFromJSON(json: any): OffsetPagination {
  return OffsetPaginationFromJSONTyped(json, false);
}

export function OffsetPaginationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OffsetPagination {
  if (json == null) {
    return json;
  }
  return {
    limit: json["limit"] == null ? undefined : json["limit"],
    offset: json["offset"] == null ? undefined : json["offset"],
    total: json["total"] == null ? undefined : json["total"],
  };
}

export function OffsetPaginationToJSON(json: any): OffsetPagination {
  return OffsetPaginationToJSONTyped(json, false);
}

export function OffsetPaginationToJSONTyped(
  value?: OffsetPagination | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    limit: value["limit"],
    offset: value["offset"],
    total: value["total"],
  };
}
