/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
/**
 * Permission represents custom method descriptor to document necessary
 *  permission required to do certain action on a resource in a domain.
 * @export
 * @interface Permission
 */
export interface Permission {
  /**
   *
   * @type {string}
   * @memberof Permission
   */
  domain?: string;
  /**
   *
   * @type {string}
   * @memberof Permission
   */
  resource?: string;
  /**
   *
   * @type {string}
   * @memberof Permission
   */
  action?: string;
}

/**
 * Check if a given object implements the Permission interface.
 */
export function instanceOfPermission(value: object): value is Permission {
  return true;
}

export function PermissionFromJSON(json: any): Permission {
  return PermissionFromJSONTyped(json, false);
}

export function PermissionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Permission {
  if (json == null) {
    return json;
  }
  return {
    domain: json["domain"] == null ? undefined : json["domain"],
    resource: json["resource"] == null ? undefined : json["resource"],
    action: json["action"] == null ? undefined : json["action"],
  };
}

export function PermissionToJSON(json: any): Permission {
  return PermissionToJSONTyped(json, false);
}

export function PermissionToJSONTyped(
  value?: Permission | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    domain: value["domain"],
    resource: value["resource"],
    action: value["action"],
  };
}
