/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
import type { User } from "./User";
import {
  UserFromJSON,
  UserFromJSONTyped,
  UserToJSON,
  UserToJSONTyped,
} from "./User";

/**
 * Response body of Register new user
 * @export
 * @interface RegisterResponse
 */
export interface RegisterResponse {
  /**
   * additional message
   * @type {string}
   * @memberof RegisterResponse
   */
  message?: string;
  /**
   *
   * @type {User}
   * @memberof RegisterResponse
   */
  user?: User;
  /**
   * generated token after registered
   * @type {string}
   * @memberof RegisterResponse
   */
  token?: string;
  /**
   * refresh token for the user
   * @type {string}
   * @memberof RegisterResponse
   */
  refreshToken?: string;
}

/**
 * Check if a given object implements the RegisterResponse interface.
 */
export function instanceOfRegisterResponse(
  value: object,
): value is RegisterResponse {
  return true;
}

export function RegisterResponseFromJSON(json: any): RegisterResponse {
  return RegisterResponseFromJSONTyped(json, false);
}

export function RegisterResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RegisterResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json["message"] == null ? undefined : json["message"],
    user: json["user"] == null ? undefined : UserFromJSON(json["user"]),
    token: json["token"] == null ? undefined : json["token"],
    refreshToken:
      json["refreshToken"] == null ? undefined : json["refreshToken"],
  };
}

export function RegisterResponseToJSON(json: any): RegisterResponse {
  return RegisterResponseToJSONTyped(json, false);
}

export function RegisterResponseToJSONTyped(
  value?: RegisterResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value["message"],
    user: UserToJSON(value["user"]),
    token: value["token"],
    refreshToken: value["refreshToken"],
  };
}
