/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
/**
 * Request body of Register new user
 * @export
 * @interface RegisterRequest
 */
export interface RegisterRequest {
  /**
   * User full name
   * @type {string}
   * @memberof RegisterRequest
   */
  fullname?: string;
  /**
   * User phone number
   * @type {string}
   * @memberof RegisterRequest
   */
  phoneNumber?: string;
  /**
   * Username
   * @type {string}
   * @memberof RegisterRequest
   */
  username?: string;
  /**
   * User email
   * @type {string}
   * @memberof RegisterRequest
   */
  email?: string;
  /**
   * User Password
   * @type {string}
   * @memberof RegisterRequest
   */
  password?: string;
  /**
   *  login challenge from auth-server
   * @type {string}
   * @memberof RegisterRequest
   */
  loginChallenge?: string;
}

/**
 * Check if a given object implements the RegisterRequest interface.
 */
export function instanceOfRegisterRequest(
  value: object,
): value is RegisterRequest {
  return true;
}

export function RegisterRequestFromJSON(json: any): RegisterRequest {
  return RegisterRequestFromJSONTyped(json, false);
}

export function RegisterRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RegisterRequest {
  if (json == null) {
    return json;
  }
  return {
    fullname: json["fullname"] == null ? undefined : json["fullname"],
    phoneNumber: json["phoneNumber"] == null ? undefined : json["phoneNumber"],
    username: json["username"] == null ? undefined : json["username"],
    email: json["email"] == null ? undefined : json["email"],
    password: json["password"] == null ? undefined : json["password"],
    loginChallenge:
      json["loginChallenge"] == null ? undefined : json["loginChallenge"],
  };
}

export function RegisterRequestToJSON(json: any): RegisterRequest {
  return RegisterRequestToJSONTyped(json, false);
}

export function RegisterRequestToJSONTyped(
  value?: RegisterRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    fullname: value["fullname"],
    phoneNumber: value["phoneNumber"],
    username: value["username"],
    email: value["email"],
    password: value["password"],
    loginChallenge: value["loginChallenge"],
  };
}
