/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
import type { OffsetPagination } from "./OffsetPagination";
import {
  OffsetPaginationFromJSON,
  OffsetPaginationFromJSONTyped,
  OffsetPaginationToJSON,
  OffsetPaginationToJSONTyped,
} from "./OffsetPagination";
import type { CursorPagination } from "./CursorPagination";
import {
  CursorPaginationFromJSON,
  CursorPaginationFromJSONTyped,
  CursorPaginationToJSON,
  CursorPaginationToJSONTyped,
} from "./CursorPagination";

/**
 *
 * @export
 * @interface ResponseMetadata
 */
export interface ResponseMetadata {
  /**
   *
   * @type {OffsetPagination}
   * @memberof ResponseMetadata
   */
  offsetPagination?: OffsetPagination;
  /**
   *
   * @type {CursorPagination}
   * @memberof ResponseMetadata
   */
  cursorPagination?: CursorPagination;
}

/**
 * Check if a given object implements the ResponseMetadata interface.
 */
export function instanceOfResponseMetadata(
  value: object,
): value is ResponseMetadata {
  return true;
}

export function ResponseMetadataFromJSON(json: any): ResponseMetadata {
  return ResponseMetadataFromJSONTyped(json, false);
}

export function ResponseMetadataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponseMetadata {
  if (json == null) {
    return json;
  }
  return {
    offsetPagination:
      json["offsetPagination"] == null
        ? undefined
        : OffsetPaginationFromJSON(json["offsetPagination"]),
    cursorPagination:
      json["cursorPagination"] == null
        ? undefined
        : CursorPaginationFromJSON(json["cursorPagination"]),
  };
}

export function ResponseMetadataToJSON(json: any): ResponseMetadata {
  return ResponseMetadataToJSONTyped(json, false);
}

export function ResponseMetadataToJSONTyped(
  value?: ResponseMetadata | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    offsetPagination: OffsetPaginationToJSON(value["offsetPagination"]),
    cursorPagination: CursorPaginationToJSON(value["cursorPagination"]),
  };
}
