/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
/**
 *
 * @export
 * @interface RevokePermissionResponse
 */
export interface RevokePermissionResponse {
  /**
   * Message indicating the result of the revoke operation
   * @type {string}
   * @memberof RevokePermissionResponse
   */
  message?: string;
}

/**
 * Check if a given object implements the RevokePermissionResponse interface.
 */
export function instanceOfRevokePermissionResponse(
  value: object,
): value is RevokePermissionResponse {
  return true;
}

export function RevokePermissionResponseFromJSON(
  json: any,
): RevokePermissionResponse {
  return RevokePermissionResponseFromJSONTyped(json, false);
}

export function RevokePermissionResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RevokePermissionResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json["message"] == null ? undefined : json["message"],
  };
}

export function RevokePermissionResponseToJSON(
  json: any,
): RevokePermissionResponse {
  return RevokePermissionResponseToJSONTyped(json, false);
}

export function RevokePermissionResponseToJSONTyped(
  value?: RevokePermissionResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value["message"],
  };
}
