/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
/**
 *
 * @export
 * @interface RevokePermissionRequest
 */
export interface RevokePermissionRequest {
  /**
   * ID of the user from whom the permission will be revoked
   * @type {string}
   * @memberof RevokePermissionRequest
   */
  userId?: string;
  /**
   * ID of the permission to be revoked
   * @type {string}
   * @memberof RevokePermissionRequest
   */
  permissionId?: string;
}

/**
 * Check if a given object implements the RevokePermissionRequest interface.
 */
export function instanceOfRevokePermissionRequest(
  value: object,
): value is RevokePermissionRequest {
  return true;
}

export function RevokePermissionRequestFromJSON(
  json: any,
): RevokePermissionRequest {
  return RevokePermissionRequestFromJSONTyped(json, false);
}

export function RevokePermissionRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RevokePermissionRequest {
  if (json == null) {
    return json;
  }
  return {
    userId: json["userId"] == null ? undefined : json["userId"],
    permissionId:
      json["permissionId"] == null ? undefined : json["permissionId"],
  };
}

export function RevokePermissionRequestToJSON(
  json: any,
): RevokePermissionRequest {
  return RevokePermissionRequestToJSONTyped(json, false);
}

export function RevokePermissionRequestToJSONTyped(
  value?: RevokePermissionRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    userId: value["userId"],
    permissionId: value["permissionId"],
  };
}
