/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
/**
 *
 * @export
 * @interface UserPermission
 */
export interface UserPermission {
  /**
   * id
   * @type {string}
   * @memberof UserPermission
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof UserPermission
   */
  userId?: string;
  /**
   *
   * @type {string}
   * @memberof UserPermission
   */
  permissionId?: string;
  /**
   *
   * @type {string}
   * @memberof UserPermission
   */
  createdBy?: string;
  /**
   * when role is created
   * @type {Date}
   * @memberof UserPermission
   */
  createdAt?: Date;
  /**
   * when role is updated
   * @type {Date}
   * @memberof UserPermission
   */
  updatedAt?: Date;
}

/**
 * Check if a given object implements the UserPermission interface.
 */
export function instanceOfUserPermission(
  value: object,
): value is UserPermission {
  return true;
}

export function UserPermissionFromJSON(json: any): UserPermission {
  return UserPermissionFromJSONTyped(json, false);
}

export function UserPermissionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserPermission {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    userId: json["userId"] == null ? undefined : json["userId"],
    permissionId:
      json["permissionId"] == null ? undefined : json["permissionId"],
    createdBy: json["createdBy"] == null ? undefined : json["createdBy"],
    createdAt:
      json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
    updatedAt:
      json["updatedAt"] == null ? undefined : new Date(json["updatedAt"]),
  };
}

export function UserPermissionToJSON(json: any): UserPermission {
  return UserPermissionToJSONTyped(json, false);
}

export function UserPermissionToJSONTyped(
  value?: UserPermission | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    userId: value["userId"],
    permissionId: value["permissionId"],
    createdBy: value["createdBy"],
    createdAt:
      value["createdAt"] == null
        ? value["createdAt"]
        : value["createdAt"].toISOString(),
    updatedAt:
      value["updatedAt"] == null
        ? value["updatedAt"]
        : value["updatedAt"].toISOString(),
  };
}
