/* tslint:disable */
/* eslint-disable */
/**
 * Authentication Domain
 * Identity Service, Auth Service, Skoola Permission Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../../../../shared/runtime";
import type { Address } from "./Address";
import {
  AddressFromJSON,
  AddressFromJSONTyped,
  AddressToJSON,
  AddressToJSONTyped,
} from "./Address";

/**
 * User entity
 * @export
 * @interface User
 */
export interface User {
  /**
   * User ID
   * @type {string}
   * @memberof User
   */
  id?: string;
  /**
   * User full name
   * @type {string}
   * @memberof User
   */
  fullname?: string;
  /**
   * User username
   * @type {string}
   * @memberof User
   */
  username?: string;
  /**
   * User phone number
   * @type {string}
   * @memberof User
   */
  phoneNumber?: string;
  /**
   * User email
   * @type {string}
   * @memberof User
   */
  email?: string;
  /**
   * User profile pict name
   * @type {string}
   * @memberof User
   */
  profilePic?: string;
  /**
   *
   * @type {Address}
   * @memberof User
   */
  address?: Address;
  /**
   * User gender
   * @type {string}
   * @memberof User
   */
  gender?: UserGenderEnum;
  /**
   * User Date of Birth
   * @type {Date}
   * @memberof User
   */
  dateOfBirth?: Date;
  /**
   * User Place of Birth
   * @type {string}
   * @memberof User
   */
  placeOfBirth?: string;
  /**
   *
   * @type {string}
   * @memberof User
   */
  roleType?: UserRoleTypeEnum;
  /**
   * Represent user status
   * @type {string}
   * @memberof User
   */
  status?: UserStatusEnum;
  /**
   * Time when user is created
   * @type {Date}
   * @memberof User
   */
  createdAt?: Date;
  /**
   * Time when user data updated
   * @type {Date}
   * @memberof User
   */
  updatedAt?: Date;
}

/**
 * @export
 * @enum {string}
 */
export enum UserGenderEnum {
  GenderUnspecified = "GENDER_UNSPECIFIED",
  Male = "MALE",
  Female = "FEMALE",
}
/**
 * @export
 * @enum {string}
 */
export enum UserRoleTypeEnum {
  User = "USER",
}
/**
 * @export
 * @enum {string}
 */
export enum UserStatusEnum {
  UserStatusUnspecified = "USER_STATUS_UNSPECIFIED",
  UserStatusActive = "USER_STATUS_ACTIVE",
  UserStatusInactive = "USER_STATUS_INACTIVE",
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
  return true;
}

export function UserFromJSON(json: any): User {
  return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): User {
  if (json == null) {
    return json;
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    fullname: json["fullname"] == null ? undefined : json["fullname"],
    username: json["username"] == null ? undefined : json["username"],
    phoneNumber: json["phoneNumber"] == null ? undefined : json["phoneNumber"],
    email: json["email"] == null ? undefined : json["email"],
    profilePic: json["profilePic"] == null ? undefined : json["profilePic"],
    address:
      json["address"] == null ? undefined : AddressFromJSON(json["address"]),
    gender: json["gender"] == null ? undefined : json["gender"],
    dateOfBirth:
      json["dateOfBirth"] == null ? undefined : new Date(json["dateOfBirth"]),
    placeOfBirth:
      json["placeOfBirth"] == null ? undefined : json["placeOfBirth"],
    roleType: json["roleType"] == null ? undefined : json["roleType"],
    status: json["status"] == null ? undefined : json["status"],
    createdAt:
      json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
    updatedAt:
      json["updatedAt"] == null ? undefined : new Date(json["updatedAt"]),
  };
}

export function UserToJSON(json: any): User {
  return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(
  value?: User | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value["id"],
    fullname: value["fullname"],
    username: value["username"],
    phoneNumber: value["phoneNumber"],
    email: value["email"],
    profilePic: value["profilePic"],
    address: AddressToJSON(value["address"]),
    gender: value["gender"],
    dateOfBirth:
      value["dateOfBirth"] == null
        ? value["dateOfBirth"]
        : value["dateOfBirth"].toISOString(),
    placeOfBirth: value["placeOfBirth"],
    roleType: value["roleType"],
    status: value["status"],
    createdAt:
      value["createdAt"] == null
        ? value["createdAt"]
        : value["createdAt"].toISOString(),
    updatedAt:
      value["updatedAt"] == null
        ? value["updatedAt"]
        : value["updatedAt"].toISOString(),
  };
}
